CREATE TABLE [dbo].[ggz_zorgprestatie] (
    [ggz_zorgprestatie_id]                  INT             IDENTITY (1, 1) NOT NULL,
    [ggz_toeslag_id]                        INT             DEFAULT ((0)) NOT NULL,
    [ggz_traject_ok]                        INT             NOT NULL,
    [ggz_zorgprestatie_ok]                  INT             NOT NULL,
    [ggz_zorgprestatie_dim_id]              INT             NULL,
    [uitvoerder_zorgverlener_id]            INT             NULL,
    [uitvoer_datumtijd]                     SMALLDATETIME   NULL,
    [duur_minuten]                          INT             NULL,
    [duur_dagen]                            INT             NULL,
    [aantal]                                INT             NULL,
    [ggz_opname_id]                         INT             NULL,
    [opname_nr]                             INT             NULL,
    [afspraak_nr]                           INT             NULL,
    [duur_minuten_afspraak]                 INT             NULL,
    [verzekeraar_id]                        NUMERIC (18)    NULL,
    [klinisch_jn]                           VARCHAR (1)     NULL,
    [omzet]                                 DECIMAL (12, 2) NULL,
    [ggz_zorgprestatie_dim_id_toeslag]      INT             NULL,
    [bedrag_toeslag]                        NUMERIC (12, 2) NULL,
    [normtijd_indirect]                     NUMERIC (7, 3)  NULL,
    [doorberekende_directe_tijd]            NUMERIC (7, 3)  NULL,
    [directe_tijd_groepsconsulten]          NUMERIC (7, 3)  NULL,
    [patient_nr]                            INT             NULL,
    [ggz_regiebehandelaar_id_zorgprestatie] INT             NULL,
    [ggz_diagnose_zpm_id_zorgprestatie]     INT             NULL,
    [bedrag_totaal]                         NUMERIC (12, 2) NULL,
    [werknemer_id]                          VARCHAR (10)    NULL,
    [ggz_dbc_id_oud]                        INT             NULL,
    [traject_ggz_zorglabel_id]              INT             NULL,
    [traject_startdatum]                    DATETIME        NULL,
    [traject_einddatum]                     DATETIME        NULL,
    [traject_registratiedatum]              DATETIME        NULL,
    [traject_privacy]                       BIT             NULL,
    [traject_financieel_type]               SMALLINT        NULL,
    [traject_agb_verwijzer]                 VARCHAR (12)    NULL,
    [traject_agb_verwijzer_id]              INT             NULL,
    [traject_ggz_verwijstype_id]            INT             NULL,
    [traject_tariefniveau]                  INT             NULL,
    [creatie_datum]                         DATETIME        NOT NULL,
    [mutatie_datum]                         DATETIME        NOT NULL,
    [verwijderd_datum]                      DATETIME        NULL,
    [HuidigeDiagnoseJn]                     VARCHAR (1)     NULL,
    [HuidigeRegiebehandelaarJn]             VARCHAR (1)     NULL,
    [HuidigeFaseInTraject]                  VARCHAR (14)    NULL,
    [gc_geen_tijd_ind]                      BIT             NULL,
    [verzekeraar_tarief]                    NUMERIC (12, 2) NULL,
    [regiebehandelaar_huidige_id]           INT             NULL,
    [diagnose_huidige_id]                   INT             NULL,
    [omzet_vz]                              DECIMAL (12, 2) NULL,
    [vz_tarief_toeslag_ind]                 VARCHAR (16)    NULL,
    [vz_tarief_ind]                         VARCHAR (1)     NULL,
    [ggz_verzekeraar_id]                    INT             NULL,
    [factuur_foutcode]                      INT             NULL,
    [factuur_statuscode]                    INT             NULL,
    [factuur_methodecode]                   INT             NULL,
    CONSTRAINT [PK_ggz_zorgprestatie_id] PRIMARY KEY CLUSTERED ([ggz_traject_ok] ASC, [ggz_zorgprestatie_ok] ASC, [ggz_toeslag_id] ASC) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE)
);







