CREATE TABLE [dbo].[Clients] (
    [Id]                                BIGINT          IDENTITY (1, 1) NOT NULL,
    [CreatedBy]                         NVARCHAR (50)   NULL,
    [Created]                           DATETIME2 (7)   NOT NULL,
    [LastModifiedBy]                    NVARCHAR (50)   NULL,
    [LastModified]                      DATETIME2 (7)   NULL,
    [ClientNumber]                      NVARCHAR (20)   NOT NULL,
    [NationalIdentifier]                INT             NULL,
    [BirthName]                         NVARCHAR (25)   NULL,
    [Initials]                          NVARCHAR (6)    NULL,
    [FirstName]                         NVARCHAR (50)   NULL,
    [PartnerName]                       NVARCHAR (25)   NULL,
    [PrefixPartnerName]                 NVARCHAR (10)   NULL,
    [Street]                            NVARCHAR (100)  NULL,
    [HouseNumber]                       INT             NULL,
    [HouseNumberAddition]               NVARCHAR (6)    NULL,
    [PostalCode]                        NVARCHAR (10)   NULL,
    [City]                              NVARCHAR (50)   NULL,
    [Gender]                            TINYINT         NOT NULL,
    [DateOfBirth]                       DATETIME2 (7)   NULL,
    [PhoneNumber]                       NVARCHAR (20)   NULL,
    [Deceased]                          BIT             NOT NULL,
    [Removed]                           BIT             NOT NULL,
    [OrganizationId]                    BIGINT          NOT NULL,
    [CorrespondenceStreet]              NVARCHAR (100)  NULL,
    [CorrespondenceCity]                NVARCHAR (50)   NULL,
    [CorrespondenceCountryId]           INT             NULL,
    [CorrespondencePostalCode]          NVARCHAR (10)   NULL,
    [CorresponenceAttentionOf]          NVARCHAR (50)   NULL,
    [CountryId]                         INT             NULL,
    [Email]                             NVARCHAR (100)  NULL,
    [PhoneNumberMobile]                 NVARCHAR (20)   NULL,
    [Referrer]                          NVARCHAR (50)   NULL,
    [ValidationError]                   BIT             NOT NULL,
    [PhoneNumberWork]                   NVARCHAR (20)   NULL,
    [PrefixBirthName]                   NVARCHAR (10)   NULL,
    [Picture]                           VARBINARY (MAX) NULL,
    [Title]                             TINYINT         NOT NULL,
    [DateOfDeath]                       DATETIME2 (7)   NULL,
    [UseDifferentCorrespondenceAddress] BIT             NOT NULL,
    [CorrespondenceHouseNumber]         INT             NULL,
    [CorrespondenceHouseNumberAddition] NVARCHAR (6)    NULL,
    [FullName]                          NVARCHAR (73)   NULL,
    [ExternalId]                        BIGINT          NULL
)
WITH (DATA_COMPRESSION = PAGE);

